### ISSUE TITLE
Please add a license file and consider renaming the repository to match the plugin file

### ISSUE THREAD

**Issue by unixorn** [fruitydog/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I only add themes with a license file because some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

The plugin repository's name is very generic. Please consider renaming it to kiwi.zsh-theme to match the name of the plugin file

Thanks!

**Comment by fruitydog** [comment]
Done 😄🐾
